[project]
name = "cam-functions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.14",
    "mcp[cli]>=1.8.0",
    "requests>=2.32.3",
    "uvicorn>=0.34.2",
]
